[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/bash"
args = ["--login"]

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.98

# [keyboard]
# bindings = [
#   { key = "F11", action = "ToggleFullscreen" },
# ]
