# Alacritty Ash Theme

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#ffffff"
foreground = "#0a0a0a"

[colors.selection]
text = "#ffffff"
background = "#0a0a0a"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.normal]
black = "#c0c0c0"
red = "#0a0a0a"
green = "#0a0a0a"
yellow = "#0a0a0a"
blue = "#0a0a0a"
magenta = "#0a0a0a"
cyan = "#0a0a0a"
white = "#0a0a0a"

[colors.bright]
black = "#d0d0d0"
red = "#0a0a0a"
green = "#0a0a0a"
yellow = "#0a0a0a"
blue = "#0a0a0a"
magenta = "#0a0a0a"
cyan = "#0a0a0a"
white = "#0a0a0a"

